### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by swcoleman** [barrysampson/omnifocus-task-completion-to-devonthink#1]
I am getting the following error when I run the script.

error "OmniFocus got an error: Can’t make context of task id \"g6AO4MKtbwk.19\" of default document into type specifier." number -1700 from context of task id "g6AO4MKtbwk.19" of default document to specifier

**Comment by barrysampson** [comment]
I switched to Windows a little while ago and no longer have a Mac, so I'm no longer able to work on this.
